/**
 * 逆合成パズル（合成ルートビルダー）- データ定義
 * 目標化合物（Target）から逆算し、出発物質から最短手数で合成する思考パズル
 */

export const RETRO_PUZZLES = [
  {
    id: "puzzle1",
    num: 1,
    title: "芳香性エステルへの最短ルート",
    target: "ethyl_acetate",
    targetName: "酢酸エチル",
    targetFormula: "CH₃COOC₂H₅",
    start: "ethylene",
    startName: "エチレン（CH₂=CH₂）",
    par: 4,
    difficulty: "中級 ★★★☆☆",
    desc: "石油化学の出発原料「エチレン」から、甘い果実臭をもつ溶媒「酢酸エチル」を4手以内で合成せよ！",
    clue: "【逆合成思考】酢酸エチルはエタノールと酢酸のエステル化で作れる。エチレンに水を付加させてエタノールを作り、2段階酸化（アセトアルデヒドを経て酢酸へ）を行ってからエステル化しよう！",
    reagents: ["h2o", "kmno4", "ethanol", "h2", "cl2", "br2"],
    catAvailable: ["none", "H2SO4_cat", "H3PO4", "Ni"],
    notes: "水付加（300℃ / リン酸）、酸化（60℃ / KMnO₄）、エステル化（60〜80℃ / 濃硫酸）が必要です。"
  },
  {
    id: "puzzle2",
    num: 2,
    title: "世界初の合成解熱薬アセトアニリド",
    target: "acetanilide",
    targetName: "アセトアニリド",
    targetFormula: "C₆H₅NHCOCH₃",
    start: "benzene",
    startName: "ベンゼン（C₆H₆）",
    par: 3,
    difficulty: "中級 ★★★☆☆",
    desc: "母体化合物「ベンゼン」を出発点として、かつて解熱鎮痛薬として市販された「アセトアニリド」を3手で合成せよ！",
    clue: "【逆合成思考】アセトアニリドはアニリンを無水酢酸でアセチル化して作る。アニリンはニトロベンゼンの還元で作れる。ニトロベンゼンはベンゼンのニトロ化だ！",
    reagents: ["hno3", "sn", "ac2o", "h2o", "cl2", "naoh"],
    catAvailable: ["none", "H2SO4_cat", "Fe"],
    notes: "ニトロ化は温水浴（50〜60℃）、スズ還元は温水浴（60〜80℃）で行います。"
  },
  {
    id: "puzzle3",
    num: 3,
    title: "太陽と炎の色 アゾ染料カップリング",
    target: "azo_dye",
    targetName: "p-ヒドロキシアゾベンゼン",
    targetFormula: "C₆H₅−N=N−C₆H₄OH",
    start: "nitrobenzene",
    startName: "ニトロベンゼン（C₆H₅NO₂）",
    par: 3,
    difficulty: "上級 ★★★★☆",
    desc: "黄色油状の「ニトロベンゼン」から、鮮やかな橙赤色のアゾ染料を3手で完成させよ！",
    clue: "【逆合成思考】アゾ染料は「塩化ベンゼンジアゾニウム」と「フェノール」のカップリング反応で生じる。アニリンを氷冷ジアゾ化し、ジアゾニウム塩の一部を加水分解してフェノールにすれば…？",
    reagents: ["sn", "nano2", "h2o", "phenol", "naoh", "hcl"],
    catAvailable: ["none", "H2SO4_cat"],
    notes: "ジアゾ化は必ず0〜5℃（氷冷）！ ジアゾニウム塩を30〜80℃で温めるとフェノールに分解します。"
  },
  {
    id: "puzzle4",
    num: 4,
    title: "奇跡の万能薬 アスピリン合成",
    target: "aspirin",
    targetName: "アセチルサリチル酸（アスピリン）",
    targetFormula: "C₆H₄(OCOCH₃)COOH",
    start: "phenol",
    startName: "フェノール（C₆H₅OH）",
    par: 2,
    difficulty: "中級 ★★★☆☆",
    desc: "消毒薬「フェノール」から、世界中で最も服用されている解熱鎮痛薬「アスピリン」を最短2手で合成せよ！",
    clue: "【逆合成思考】アスピリンはサリチル酸のフェノール性−OHを無水酢酸でアセチル化したもの。サリチル酸はフェノールナトリウムに二酸化炭素CO₂を高温高圧で吹き込む（コルベ・シュミット反応）！",
    reagents: ["co2", "ac2o", "methanol", "naoh", "h2o"],
    catAvailable: ["none", "H2SO4_cat"],
    notes: "コルベ・シュミット反応は120〜150℃（プリセット140℃）、アセチル化は温水浴（60〜80℃）です。"
  },
  {
    id: "puzzle5",
    num: 5,
    title: "日本発の国産合成繊維 ビニロン",
    target: "vinylon",
    targetName: "ビニロン（アセタール化PVA）",
    targetFormula: "環状アセタール化ポリビニルアルコール",
    start: "vinyl_acetate",
    startName: "酢酸ビニル（CH₂=CH(OCOCH₃)）",
    par: 3,
    difficulty: "上級 ★★★★☆",
    desc: "不飽和エステル「酢酸ビニル」から、京都大学の桜田一郎らが開発した高強度・耐水性繊維「ビニロン」を3手で導け！",
    clue: "【逆合成思考】ビニロンは水溶性PVAのヒドロキシ基をホルマリンでアセタール化したもの。PVAはポリ酢酸ビニル（PVAc）をNaOHでけん化して作る！",
    reagents: ["naoh", "formaldehyde", "h2o", "hcl"],
    catAvailable: ["none", "poly", "H2SO4_cat"],
    notes: "酢酸ビニルの付加重合には重合触媒、アセタール化には酸触媒（濃硫酸）が必要です。"
  },
  {
    id: "puzzle6",
    num: 6,
    title: "鋼鉄より強い蜘蛛の糸 ナイロン66",
    target: "nylon66",
    targetName: "ナイロン66（ポリアミド）",
    targetFormula: "−[CO(CH₂)₄CONH(CH₂)₆NH]ₙ−",
    start: "adipic_acid",
    startName: "アジピン酸（HOOC(CH₂)₄COOH）",
    par: 1,
    difficulty: "初級 ★☆☆☆☆",
    desc: "炭素数6のジカルボン酸「アジピン酸」から、世界初の合成繊維「ナイロン66」を1手で重縮合させよ！",
    clue: "【逆合成思考】ナイロン66はアジピン酸とジアミンの脱水縮合重合。相手となる炭素数6のジアミンは何か？",
    reagents: ["hda", "ethylene_glycol", "naoh", "h2so4"],
    catAvailable: ["none", "H2SO4_cat", "poly"],
    notes: "アジピン酸とヘキサメチレンジアミン（HDA）を室温〜温水浴（20〜60℃）で界面重縮合させます。"
  },
  {
    id: "puzzle7",
    num: 7,
    title: "グッドイヤーの奇跡 加硫ゴム",
    target: "vulcanized_rubber",
    targetName: "加硫ゴム（弾性エボナイト）",
    targetFormula: "加硫シス-1,4-ポリイソプレン",
    start: "isoprene",
    startName: "イソプレン（CH₂=C(CH₃)−CH=CH₂）",
    par: 2,
    difficulty: "中級 ★★★☆☆",
    desc: "ジエン系モノマー「イソプレン」から、自動車タイヤに不可欠な強靭な弾性をもつ「加硫ゴム」を2手で合成せよ！",
    clue: "【逆合成思考】加硫ゴムは生ゴム（ポリイソプレン）の分子鎖間に硫黄架橋（−S−S−）を導入したもの。まずはイソプレンを重合させて生ゴムを作ろう！",
    reagents: ["sulfur", "o2", "h2", "cl2"],
    catAvailable: ["none", "poly"],
    notes: "イソプレンの重合には重合触媒、生ゴムの加硫には硫黄（S）と140℃（120〜150℃）の加熱が必要です。"
  },
  {
    id: "puzzle8",
    num: 8,
    title: "生命の骨格 ジペプチドからタンパク質へ",
    target: "protein",
    targetName: "タンパク質（ポリペプチド複合体）",
    targetFormula: "ポリペプチド高分子",
    start: "glycine",
    startName: "グリシン（H₂N−CH₂−COOH）",
    par: 2,
    difficulty: "達人 ★★★★★",
    desc: "最も単純なアミノ酸「グリシン」から、生命活動を司る巨大生体高分子「タンパク質」を2手で重合させよ！",
    clue: "【逆合成思考】タンパク質は多数のアミノ酸がペプチド結合（−CO−NH−）したもの。まずはグリシンと別のアミノ酸（アラニン）を縮合させてジペプチドを作り、さらに縮合重合させよう！",
    reagents: ["alanine", "glycine", "glucose", "naoh"],
    catAvailable: ["none", "H2SO4_cat"],
    notes: "アミノ酸同士の温水加熱（60〜80℃）により脱水縮合してペプチド結合を形成します。"
  }
];
